apiVersion: apps/v1
kind: Deployment
metadata:
  name: josephus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: josephus-api
  template:
    metadata:
      labels:
        app: josephus-api
    spec:
      containers:
        - name: josephus-api
          image: josephus-api:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: josephus-service
spec:
  type: NodePort
  selector:
    app: josephus-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007